### ISSUE TITLE
Could not get it run on iOS device

### ISSUE THREAD

**Issue by o0160o** [msgpack/msgpack-cli#186] opened 2016-09-16 07:20 UTC
I wrote a test case like this.
[Test.cs.zip](https://github.com/msgpack/msgpack-cli/files/476271/Test.cs.zip)
This it what i got:

> Unhandled Exception: System.InvalidOperationException: An AOT error is occurred. MessagePackSerializer.PrepareType<System.Int32> is should be called in advance. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: An AOT error is occurred. MessagePackSerializer.PrepareType<System.Int32> is should be called in advance. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ExecutionEngineException: Attempting to call method 'MsgPack.Serialization.SerializationContext::GetSerializer' for which no ahead of time (AOT) code was generated.

I couldn't get it run on iOS device.
Do you have any suggestions? Thank you in advance!

**Comment by yfakariya** [comment] 2016-09-23 10:04
Sorry for delay.
Unfortunately, you must prepare **all** types you used except you use pre-generated serializers (which can do with `mpu.exe`).

I reproduced and then put following code, it worked well:
```c#
// start adding --
MsgPack.Serialization.MessagePackSerializer.PrepareType<int>();
MsgPack.Serialization.MessagePackSerializer.PrepareType<string>();
MsgPack.Serialization.MessagePackSerializer.PrepareType<AData>();
MsgPack.Serialization.MessagePackSerializer.PrepareType<BData>();
// -- end adding
MsgPack.Serialization.MessagePackSerializer.PrepareType<Dat>();
```

**Comment by o0160o** [comment] 2016-09-23 10:47
Thank you very much!

**Comment by yfakariya** [comment] 2016-09-24 09:24
No problem!
I close this because it looks solved.

**Closed by yfakariya** 2016-09-24 09:24 UTC
Labels: question
