### ISSUE TITLE
mpu.exe with mono on OSX: System.Exception: Compiler failed to produce the assembly. Output: ''

### ISSUE THREAD

**Issue by internetcoffeephone** [msgpack/msgpack-cli#80] opened 2015-05-12 17:51 UTC
I'm getting some undefinable errors when trying to generate a serializer for an extremely trivial enum, using OSX. Going to try on Windows later.
The command I'm using is
`mono mpu.exe -s /Users/xxxx/Desktop/mpack/xxxx.cs`

Full error log:
```
System.Exception: Compiler failed to produce the assembly. Output: ''
  at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
  at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
  at mpu.SerializerTargetCompiler.CompileSourceFiles (IEnumerable`1 sourceFilePathes, IEnumerable`1 referenceAssemblies, System.IO.TextWriter outputWriter, mpu.ColorizedTextWriter errorWriter) [0x00000] in <filename unknown>:0 
  at mpu.SerializerTargetCompiler.CompileTargetTypeAssembly (IEnumerable`1 sourceFilePathes, IEnumerable`1 referenceAssemblies) [0x00000] in <filename unknown>:0 
  at mpu.Program.GenerateSerializers (IList`1 sourceFilePathes, System.String[] referenceAssemblies, Boolean sourceFileIsAssembly, System.String includingPattern, System.String excludingPattern, Boolean treatWarningsAsErrors, Int32 warningLevel, MsgPack.Serialization.SerializerCodeGenerationConfiguration configuration) [0x00000] in <filename unknown>:0 
  at mpu.Program.Execute (IEnumerable`1 args) [0x00000] in <filename unknown>:0 
  at mpu.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  ```

EDIT: Works just fine on Windows. Probably some mono bug?

**Comment by yfakariya** [comment] 2015-08-16 06:52
Sorry for delay.I cannot repro it with Mono 4.0.3 in MacOS X. Please retry it with latest mpu.exe and mono.

**Comment by yfakariya** [comment] 2015-12-23 07:48
Close because this was not reproduced and no additional post... Please reopen when you face this problem again.

**Comment by jiguangdongyu** [comment] 2016-10-13 09:29
i have faced this problem again...

**Comment by yfakariya** [comment] 2016-10-16 22:20
Would you tell me the mono version?

**Comment by jiguangdongyu** [comment] 2016-10-24 00:45
I have fixed it,  this problem appeared because i have used "Class a" extends "Class b", and i serialize a but not serialize b, sorry to disturb you.

**Comment by yfakariya** [comment] 2016-10-25 01:25
No problem!

**Comment by yfakariya** [comment] 2016-10-25 01:25
Close this because it was not a msgpack issue.

**Closed by yfakariya** 2016-10-25 01:25 UTC
