### ISSUE TITLE
Trouble importing to UWP/UAP10 projects

### ISSUE THREAD

**Issue by JSalazar88** [msgpack/msgpack-cli#187] opened 2016-09-27 16:25 UTC
Where in the lib directory are the UWP/UAP dll files stored? In-case we prefer not to use nuget inclusion, and instead decide to reference the DLL's directly?

Thanks!

**Comment by yfakariya** [comment] 2016-09-27 22:56
If you want to use dll directly, the file under `lib/netstandard1.3` can be used in uwp/uap.
You can also get dll from github release page. It includes same dlls as nuget package and additional dlls for unity.

**Comment by yfakariya** [comment] 2017-05-04 00:45
I changed package structure due to #221, so uap should work correctly after 0.9.0 rc1.

**Comment by marto83** [comment] 2017-08-11 22:31
Do you know when 0.9.0 rc1 will be released? 
We use MsgPack extensively in our library and currently, we can't support UWP because of this issue.  https://github.com/ably/ably-dotnet/issues/106

Thanks

**Comment by yfakariya** [comment] 2017-08-23 12:36
About 10 days ago. Sorry for delay.

**Comment by DaTester** [comment] 2017-09-06 19:47
Hi @yfakariya  - i'm afraid we still have issue with the latest release (0.9.1) with Xamarin UWP.  The project fails to start when in release mode but works fine in run debug mode.   Not much details are provided when it fails except - "A dependent dll was not found"

**Comment by yfakariya** [comment] 2017-09-07 12:17
@DaTester
Thank you for reporting. I will investigate it. Could you tell me version of Xamarin.Forms, Visual Studio, and UWP SDKs/tools?

**Comment by DaTester** [comment] 2017-09-07 14:51
Sure thing - if you need any other info let me know
Visual Studio 2015 (Community Edition)
Xamarin SDK version 4.5.0.486
Xamarin Forms version 2.3.3.180
Microsoft.NetCore.UniversalWindowsPlatform version 5.2.3
Visual Studio Tools for Universal Window Apps SDK version 14.0.25527.01

Thanks.

**Comment by DaTester** [comment] 2017-09-17 18:18
Hi @yfakariya - any luck with this issue? I think this issue is related to #206 .

**Comment by yfakariya** [comment] 2017-09-18 10:46
@DaTester Could you upload minimal code to reproduce and debug it? I failed to reproduce this issue.

I guess this is not related to #206 because it should be solved in 0.9. #206 was caused because the package did not include `uap10.0` build and it accidentally brought native dll dependency.

**Comment by DaTester** [comment] 2017-09-18 11:16
@yfakariya,  no code needed to reproduce this issue.  Just open up new xamarin UWP project add the nuget MsgPack.Cli set project to release mode.   you will find the project fails to launch.

**Comment by DaTester** [comment] 2017-09-18 11:43
Please get the sample project (visual studio 2017 community) from the link below.  Ensure the project is set to release.
https://app.box.com/s/ljryi57x4lw3mqw2royw48wvl98bb8zq

**Comment by yfakariya** [comment] 2017-09-26 11:23
@DaTester Sorry for delay. I found that the nupkg did not include UAP build. Could you try this fixed package? https://ci.appveyor.com/api/buildjobs/3nk40pn5m0xydft1/artifacts/MsgPack.Cli.0.9.2-138.nupkg

**Comment by DaTester** [comment] 2017-09-26 13:16
This issue is fixed with the package you sent,  thanks @yfakariya 👍

**Comment by yfakariya** [comment] 2017-09-26 14:15
This bug should be fixed in 0.9.2.

**Closed by yfakariya** 2017-09-26 14:15 UTC
Labels: question
